name: CI Tests
on:
  workflow_dispatch: 
  push:
jobs: 
  cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Cypress.io
        uses: cypress-io/github-action@v4.1.0
        with: 
          run: npm run cy:run